### ISSUE TITLE
Checklist for 0.1.0 release

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#16]
- [ ] Tests for all currently implemented geoms
- [ ] Finish implementation of scale_colour_* and scale_fill_*
- [ ] Clean up readme and add documentation by geom 
- [ ] Fix geom_text and geom_label errors

**Comment by kdpsingh** [comment]
I was thinking this is in good enough shape that we should register the package. Thoughts?

Happy to help with the registration.

**Comment by kdpsingh** [comment]
I just split off TidierData into its own package and am planning to get the other Tidier packages registered. Once they have been registered, will convert Tidier.jl into a meta-package.

**Comment by rdboyes** [comment]
I’d appreciate the help - I’m not sure exactly how to register it. There are still some things that don’t work as advertised and I was going to fix them before registering, but I won’t have a lot of time to work on it in the next month so if you want to just go ahead and register we can fix it after the fact

**Comment by kdpsingh** [comment]
Yeah I think let's plan to register it and then we can continue to improve it. I'll take care of the registration. Once it's registered, it's super easy to push updates to the registry.
