### ISSUE TITLE
0.8.0 Release Checklist

### ISSUE THREAD

**Issue by rdboyes** [TidierOrg/TidierPlots.jl#73]
- [x] https://github.com/TidierOrg/TidierPlots.jl/issues/61
- [x] https://github.com/TidierOrg/TidierPlots.jl/issues/67
- [ ] #104 
- [ ] #80
- [x] https://github.com/TidierOrg/TidierPlots.jl/issues/74
- [x] #82
- [x] #86 
- [x] #93

**Comment by adknudson** [comment]
Suggestion:

- [ ] Fully document geoms
